### ISSUE TITLE
TRN

### ISSUE THREAD

**Issue by djgrazzy** [LevonBecker/zip-sqlbackups#1]
I'm not sure the instructions cover changing lines 146+147 if wanting to zip trn.

```
                    $zipfile = ($file -replace 'trn','zip')
                    $zipfullname = ($file.fullname -replace 'trn','zip')
```

Great script, Thanks
I may look at adding a rotation on the log file as it appears to grow.

**Comment by LevonBecker** [comment]
Sorry totally missed this forever ago. Thanks for submitting issue though. Going to close for now. I don't have time for this project. Glad it helped!
